import { write } from "./fs.js";

// The Assets CRUD reference feature: assetsApi, AssetForm, AssetFiltersPanel, AssetsPage.
export async function writeAssetsFeature(root: string): Promise<void> {
  await write(root, "src/features/assets/assetsApi.ts", [
    "import { blocksClient } from \"../../lib/blocks/client\";",
    "",
    "export const ASSET_CATEGORIES = [\"Laptop\", \"Monitor\", \"Phone\", \"Furniture\", \"Other\"] as const;",
    "export const ASSET_STATUSES = [\"Available\", \"Assigned\", \"Maintenance\", \"Retired\"] as const;",
    "",
    "export type Asset = Record<string, unknown> & {",
    "  itemId?: string;",
    "  id?: string;",
    "  name?: string;",
    "  assetTag?: string;",
    "  category?: string;",
    "  status?: string;",
    "  assignedTo?: string;",
    "  value?: number;",
    "};",
    "",
    "export type AssetInput = {",
    "  assetTag: string;",
    "  assignedTo: string;",
    "  category: string;",
    "  name: string;",
    "  status: string;",
    "  value: number;",
    "};",
    "",
    "// Advanced filters here are applied client-side. The collection helper uses",
    "// Data Gateway GraphQL and sends only paging plus the optional search filter",
    "// below, so category/status/value filters narrow the page already fetched.",
    "export type AssetFilters = { category?: string; maxValue?: number; minValue?: number; status?: string };",
    "",
    "const assets = blocksClient.data.collection<Asset>(\"Asset\", {",
    "  fields: [\"name\", \"assetTag\", \"category\", \"status\", \"assignedTo\", \"value\"]",
    "});",
    "",
    "export async function listAssets({ page, pageSize, search }: { page: number; pageSize: number; search: string }) {",
    "  const response = await assets.list({",
    "    pageNo: page,",
    "    pageSize,",
    "    filter: search ? { name: { $regex: search, $options: \"i\" } } : undefined",
    "  });",
    "  return normalizeAssetList(response);",
    "}",
    "",
    "export function createAsset(input: AssetInput) {",
    "  return assets.create(input);",
    "}",
    "",
    "export function updateAsset(asset: Asset) {",
    "  const id = assetId(asset);",
    "  return assets.update(id, asset);",
    "}",
    "",
    "export function deleteAsset(asset: Asset) {",
    "  return assets.delete(assetId(asset));",
    "}",
    "",
    "export function assetId(asset: Asset): string {",
    "  const id = asset.itemId ?? asset.id;",
    "  if (!id) throw new Error(\"Asset item id is missing.\");",
    "  return String(id);",
    "}",
    "",
    "export function matchesFilters(asset: Asset, filters: AssetFilters): boolean {",
    "  if (filters.category && asset.category !== filters.category) return false;",
    "  if (filters.status && asset.status !== filters.status) return false;",
    "",
    "  const value = Number(asset.value ?? 0);",
    "  if (filters.minValue !== undefined && value < filters.minValue) return false;",
    "  if (filters.maxValue !== undefined && value > filters.maxValue) return false;",
    "",
    "  return true;",
    "}",
    "",
    "function normalizeAssetList(response: unknown): { items: Asset[]; totalCount: number } {",
    "  const record = response as { data?: { getAssets?: { items?: Asset[]; totalCount?: number }; items?: Asset[]; totalCount?: number } | Asset[]; items?: Asset[]; totalCount?: number };",
    "  if (Array.isArray(record.data)) return { items: record.data, totalCount: record.data.length };",
    "  const gateway = record.data?.getAssets;",
    "  const items = gateway?.items ?? record.data?.items ?? record.items ?? [];",
    "  return { items, totalCount: gateway?.totalCount ?? record.data?.totalCount ?? record.totalCount ?? items.length };",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/features/assets/AssetForm.tsx", [
    "import { useEffect, useState } from \"react\";",
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "import { FormField } from \"../../shared/ui/FormField\";",
    "import { ASSET_CATEGORIES, ASSET_STATUSES } from \"./assetsApi\";",
    "import type { Asset, AssetInput } from \"./assetsApi\";",
    "",
    "const EMPTY: AssetInput = { assetTag: \"\", assignedTo: \"\", category: ASSET_CATEGORIES[0], name: \"\", status: ASSET_STATUSES[0], value: 0 };",
    "",
    "export function AssetForm({ asset, onCancel, onSubmit, saving }: {",
    "  asset?: Asset;",
    "  onCancel: () => void;",
    "  onSubmit: (input: AssetInput) => void;",
    "  saving: boolean;",
    "}) {",
    "  const { t } = useT();",
    "  const [value, setValue] = useState<AssetInput>(EMPTY);",
    "",
    "  useEffect(() => {",
    "    setValue(asset ? {",
    "      assetTag: String(asset.assetTag ?? \"\"),",
    "      assignedTo: String(asset.assignedTo ?? \"\"),",
    "      category: String(asset.category ?? ASSET_CATEGORIES[0]),",
    "      name: String(asset.name ?? \"\"),",
    "      status: String(asset.status ?? ASSET_STATUSES[0]),",
    "      value: Number(asset.value ?? 0)",
    "    } : EMPTY);",
    "  }, [asset]);",
    "",
    "  function update<K extends keyof AssetInput>(key: K, next: AssetInput[K]) {",
    "    setValue((current) => ({ ...current, [key]: next }));",
    "  }",
    "",
    "  return (",
    "    <form className=\"form-grid\" onSubmit={(event) => { event.preventDefault(); onSubmit(value); }}>",
    "      <FormField label={t(\"assets.name\")} required value={value.name} onChange={(event) => update(\"name\", event.target.value)} />",
    "      <FormField label={t(\"assets.assetTag\")} required value={value.assetTag} onChange={(event) => update(\"assetTag\", event.target.value)} />",
    "      <label className=\"form-field\">",
    "        <span>{t(\"assets.category\")}</span>",
    "        <select value={value.category} onChange={(event) => update(\"category\", event.target.value)}>",
    "          {ASSET_CATEGORIES.map((category) => <option key={category}>{category}</option>)}",
    "        </select>",
    "      </label>",
    "      <label className=\"form-field\">",
    "        <span>{t(\"assets.status\")}</span>",
    "        <select value={value.status} onChange={(event) => update(\"status\", event.target.value)}>",
    "          {ASSET_STATUSES.map((status) => <option key={status}>{status}</option>)}",
    "        </select>",
    "      </label>",
    "      <FormField label={t(\"assets.assignedTo\")} value={value.assignedTo} onChange={(event) => update(\"assignedTo\", event.target.value)} />",
    "      <FormField label={t(\"assets.value\")} min={0} type=\"number\" value={value.value} onChange={(event) => update(\"value\", Number(event.target.value))} />",
    "      <div className=\"form-actions\">",
    "        <button className=\"icon-button\" type=\"button\" onClick={onCancel}>{t(\"common.cancel\")}</button>",
    "        <button className=\"primary-button\" disabled={saving || !value.name || !value.assetTag} type=\"submit\">{saving ? t(\"common.loading\") : t(\"common.save\")}</button>",
    "      </div>",
    "    </form>",
    "  );",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/features/assets/AssetFilters.tsx", [
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "import { ASSET_CATEGORIES, ASSET_STATUSES } from \"./assetsApi\";",
    "import type { AssetFilters as AssetFiltersValue } from \"./assetsApi\";",
    "",
    "function numberOrUndefined(raw: string): number | undefined {",
    "  return raw === \"\" ? undefined : Number(raw);",
    "}",
    "",
    "export function AssetFiltersPanel({ filters, onChange, onClear }: {",
    "  filters: AssetFiltersValue;",
    "  onChange: (next: AssetFiltersValue) => void;",
    "  onClear: () => void;",
    "}) {",
    "  const { t } = useT();",
    "",
    "  return (",
    "    <div className=\"panel\">",
    "      <div className=\"filter-grid\">",
    "        <label className=\"form-field\">",
    "          <span>{t(\"assets.category\")}</span>",
    "          <select value={filters.category ?? \"\"} onChange={(event) => onChange({ ...filters, category: event.target.value || undefined })}>",
    "            <option value=\"\">{t(\"assets.filters.any\")}</option>",
    "            {ASSET_CATEGORIES.map((category) => <option key={category} value={category}>{category}</option>)}",
    "          </select>",
    "        </label>",
    "        <label className=\"form-field\">",
    "          <span>{t(\"assets.status\")}</span>",
    "          <select value={filters.status ?? \"\"} onChange={(event) => onChange({ ...filters, status: event.target.value || undefined })}>",
    "            <option value=\"\">{t(\"assets.filters.any\")}</option>",
    "            {ASSET_STATUSES.map((status) => <option key={status} value={status}>{status}</option>)}",
    "          </select>",
    "        </label>",
    "        <FormFieldNumber label={t(\"assets.filters.minValue\")} value={filters.minValue} onChange={(next) => onChange({ ...filters, minValue: next })} />",
    "        <FormFieldNumber label={t(\"assets.filters.maxValue\")} value={filters.maxValue} onChange={(next) => onChange({ ...filters, maxValue: next })} />",
    "      </div>",
    "      <div className=\"form-actions\">",
    "        <button className=\"link-button\" type=\"button\" onClick={onClear}>{t(\"assets.filters.clear\")}</button>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "function FormFieldNumber({ label, onChange, value }: { label: string; onChange: (next: number | undefined) => void; value: number | undefined }) {",
    "  return (",
    "    <label className=\"form-field\">",
    "      <span>{label}</span>",
    "      <input min={0} type=\"number\" value={value ?? \"\"} onChange={(event) => onChange(numberOrUndefined(event.target.value))} />",
    "    </label>",
    "  );",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/features/assets/AssetsPage.tsx", [
    "import { useMutation, useQuery, useQueryClient } from \"@tanstack/react-query\";",
    "import { Boxes, Edit3, Plus, RefreshCw, Search, SlidersHorizontal, Trash2 } from \"lucide-react\";",
    "import { useMemo, useState } from \"react\";",
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "import { ActionButton } from \"../../shared/ui/ActionButton\";",
    "import { ConfirmDialog } from \"../../shared/ui/ConfirmDialog\";",
    "import { DataTable } from \"../../shared/ui/DataTable\";",
    "import type { Column } from \"../../shared/ui/DataTable\";",
    "import { EmptyState } from \"../../shared/ui/EmptyState\";",
    "import { ErrorState } from \"../../shared/ui/ErrorState\";",
    "import { Modal } from \"../../shared/ui/Modal\";",
    "import { PageHeader } from \"../../shared/ui/PageHeader\";",
    "import { StatusPill } from \"../../shared/ui/StatusPill\";",
    "import { AssetFiltersPanel } from \"./AssetFilters\";",
    "import { AssetForm } from \"./AssetForm\";",
    "import { assetId, createAsset, deleteAsset, listAssets, matchesFilters, updateAsset } from \"./assetsApi\";",
    "import type { Asset, AssetFilters, AssetInput } from \"./assetsApi\";",
    "",
    "const PAGE_SIZES = [10, 25, 50] as const;",
    "",
    "export function AssetsPage() {",
    "  const { t } = useT();",
    "  const queryClient = useQueryClient();",
    "  const [page, setPage] = useState(1);",
    "  const [pageSize, setPageSize] = useState<(typeof PAGE_SIZES)[number]>(PAGE_SIZES[0]);",
    "  const [search, setSearch] = useState(\"\");",
    "  const [filtersOpen, setFiltersOpen] = useState(false);",
    "  const [filters, setFilters] = useState<AssetFilters>({});",
    "  const [editing, setEditing] = useState<Asset | undefined>();",
    "  const [creating, setCreating] = useState(false);",
    "  const [deleting, setDeleting] = useState<Asset | undefined>();",
    "",
    "  const assets = useQuery({",
    "    queryFn: () => listAssets({ page, pageSize, search }),",
    "    queryKey: [\"assets\", page, pageSize, search]",
    "  });",
    "",
    "  const invalidate = () => queryClient.invalidateQueries({ queryKey: [\"assets\"] });",
    "  const create = useMutation({ mutationFn: createAsset, onSuccess: () => { setCreating(false); void invalidate(); } });",
    "  const update = useMutation({ mutationFn: updateAsset, onSuccess: () => { setEditing(undefined); void invalidate(); } });",
    "  const remove = useMutation({ mutationFn: deleteAsset, onSuccess: () => { setDeleting(undefined); void invalidate(); } });",
    "",
    "  const allRows = assets.data?.items ?? [];",
    "  const totalCount = assets.data?.totalCount ?? 0;",
    "  const pageCount = Math.max(1, Math.ceil(totalCount / pageSize));",
    "  const activeFilterCount = Object.values(filters).filter((value) => value !== undefined).length;",
    "",
    "  // See the comment on AssetFilters in assetsApi.ts -- this narrows the page",
    "  // Data already returned rather than querying the server per field.",
    "  const rows = useMemo(() => allRows.filter((asset) => matchesFilters(asset, filters)), [allRows, filters]);",
    "",
    "  const columns = useMemo<Column<Asset>[]>(() => [",
    "    { key: \"name\", header: t(\"assets.name\"), render: (row) => <strong>{String(row.name ?? \"-\")}</strong> },",
    "    { key: \"assetTag\", header: t(\"assets.assetTag\"), render: (row) => <code className=\"mono\">{String(row.assetTag ?? \"-\")}</code> },",
    "    { key: \"category\", header: t(\"assets.category\"), render: (row) => String(row.category ?? \"-\") },",
    "    { key: \"status\", header: t(\"assets.status\"), render: (row) => <StatusPill tone={row.status === \"Available\" ? \"good\" : row.status === \"Maintenance\" ? \"warn\" : \"neutral\"}>{String(row.status ?? \"-\")}</StatusPill> },",
    "    { key: \"assignedTo\", header: t(\"assets.assignedTo\"), render: (row) => String(row.assignedTo || \"-\") },",
    "    { key: \"value\", header: t(\"assets.value\"), render: (row) => `$${Number(row.value ?? 0).toFixed(2)}` },",
    "    { key: \"actions\", header: t(\"assets.actions\"), render: (row) => (",
    "      <div className=\"row-actions\">",
    "        <ActionButton variant=\"icon\" title={t(\"assets.edit\")} icon={<Edit3 size={16} />} onClick={() => setEditing(row)} />",
    "        <ActionButton variant=\"icon\" title={t(\"common.delete\")} icon={<Trash2 size={16} />} onClick={() => setDeleting(row)} />",
    "      </div>",
    "    ) }",
    "  ], [t]);",
    "",
    "  function submit(input: AssetInput) {",
    "    if (editing) update.mutate({ ...editing, ...input });",
    "    else create.mutate(input);",
    "  }",
    "",
    "  return (",
    "    <section>",
    "      <PageHeader",
    "        title={t(\"assets.title\")}",
    "        subtitle={t(\"assets.subtitle\")}",
    "        actions={<button className=\"primary-button\" onClick={() => setCreating(true)}><Plus size={16} /> {t(\"assets.create\")}</button>}",
    "      />",
    "",
    "      <div className=\"toolbar\">",
    "        <label className=\"search-box\">",
    "          <Search size={16} />",
    "          <input aria-label={t(\"assets.search\")} placeholder={t(\"assets.search\")} value={search} onChange={(event) => { setPage(1); setSearch(event.target.value); }} />",
    "        </label>",
    "        <div className=\"toolbar-actions\">",
    "          <ActionButton",
    "            variant={activeFilterCount > 0 ? \"primary\" : \"icon\"}",
    "            title={t(\"assets.filters.toggle\")}",
    "            icon={<SlidersHorizontal size={16} />}",
    "            onClick={() => setFiltersOpen((value) => !value)}",
    "          >",
    "            {activeFilterCount > 0 ? `${t(\"assets.filters.toggle\")} (${activeFilterCount})` : undefined}",
    "          </ActionButton>",
    "          <ActionButton variant=\"icon\" title={t(\"common.refresh\")} icon={<RefreshCw size={16} />} onClick={() => assets.refetch()} />",
    "        </div>",
    "      </div>",
    "",
    "      {filtersOpen ? <AssetFiltersPanel filters={filters} onChange={setFilters} onClear={() => setFilters({})} /> : null}",
    "",
    "      {assets.isError ? <ErrorState message=\"Could not load assets from Blocks Data.\" onRetry={() => assets.refetch()} /> : null}",
    "",
    "      {assets.isLoading ? <div className=\"panel\">{t(\"common.loading\")}</div> : rows.length > 0 ? <DataTable columns={columns} rows={rows} /> : (",
    "        <EmptyState",
    "          icon={<Boxes size={28} />}",
    "          title={t(\"assets.empty\")}",
    "          description={activeFilterCount > 0 ? t(\"assets.filters.empty\") : \"Add the first Assets collection item to see the table flow.\"}",
    "          action={<button className=\"primary-button\" onClick={() => setCreating(true)}><Plus size={16} /> {t(\"assets.create\")}</button>}",
    "        />",
    "      )}",
    "",
    "      <div className=\"pagination\">",
    "        <span className=\"pagination-count\">{totalCount} asset(s)</span>",
    "        <div className=\"pagination-controls\">",
    "          <label className=\"pagination-size\">",
    "            <span>{t(\"assets.pagination.rows\")}</span>",
    "            <select value={pageSize} onChange={(event) => { setPage(1); setPageSize(Number(event.target.value) as (typeof PAGE_SIZES)[number]); }}>",
    "              {PAGE_SIZES.map((size) => <option key={size} value={size}>{size}</option>)}",
    "            </select>",
    "          </label>",
    "          <button className=\"icon-button\" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>Previous</button>",
    "          <span>Page {page} of {pageCount}</span>",
    "          <button className=\"icon-button\" disabled={page >= pageCount} onClick={() => setPage((value) => value + 1)}>Next</button>",
    "        </div>",
    "      </div>",
    "",
    "      {creating || editing ? (",
    "        <Modal title={editing ? t(\"assets.edit\") : t(\"assets.create\")} onClose={() => { setCreating(false); setEditing(undefined); }}>",
    "          <AssetForm asset={editing} saving={create.isPending || update.isPending} onCancel={() => { setCreating(false); setEditing(undefined); }} onSubmit={submit} />",
    "        </Modal>",
    "      ) : null}",
    "",
    "      {deleting ? (",
    "        <ConfirmDialog",
    "          title={t(\"assets.delete.title\")}",
    "          message={`Delete ${String(deleting.name ?? assetId(deleting))}?`}",
    "          onCancel={() => setDeleting(undefined)}",
    "          onConfirm={() => remove.mutate(deleting)}",
    "        />",
    "      ) : null}",
    "    </section>",
    "  );",
    "}",
    ""
  ].join("\n"));

}
