import { write } from "./fs.js";

// Standalone auth-flow screens: LoginPage, CallbackPage, ErrorPage, NotFoundPage.
export async function writeAuthPages(root: string): Promise<void> {
  await write(root, "src/features/auth/LoginPage.tsx", [
    "import { Activity, LogIn } from \"lucide-react\";",
    "import { useState } from \"react\";",
    "import { useAuth } from \"../../app/providers/AuthProvider\";",
    "import { isLoginConfigured } from \"../../lib/blocks/config\";",
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "import { Alert } from \"../../shared/ui/Alert\";",
    "",
    "export function LoginPage({ returnTo }: { returnTo?: string }) {",
    "  const { login } = useAuth();",
    "  const [pending, setPending] = useState(false);",
    "  const [error, setError] = useState<string | undefined>();",
    "  const { t } = useT();",
    "  const configured = isLoginConfigured();",
    "",
    "  async function handleLogin() {",
    "    setError(undefined);",
    "    setPending(true);",
    "    try {",
    "      await login(returnTo);",
    "    } catch (caught) {",
    "      setError((caught as Error).message);",
    "      setPending(false);",
    "    }",
    "  }",
    "",
    "  return (",
    "    <div className=\"auth-screen\">",
    "      <div className=\"auth-card\">",
    "        <div className=\"auth-brand\"><span className=\"brand-mark\"><Activity size={18} /></span><span>{t(\"app.name\")}</span></div>",
    "        <h2>{t(\"auth.welcome\")}</h2>",
    "        <p>{t(\"auth.subtitle\")}</p>",
    "        {!configured ? (",
    "          <Alert tone=\"warn\">",
    "            {t(\"auth.notConfigured\")} <code>{window.location.origin}/login/callback</code>",
    "          </Alert>",
    "        ) : null}",
    "        {error ? <Alert tone=\"error\">{error}</Alert> : null}",
    "        <button className=\"primary-button auth-submit\" disabled={!configured || pending} onClick={handleLogin}>",
    "          <LogIn size={18} /> {pending ? t(\"auth.redirecting\") : t(\"auth.continue\")}",
    "        </button>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/features/auth/CallbackPage.tsx", [
    "import { useEffect, useRef, useState } from \"react\";",
    "import { useAuth } from \"../../app/providers/AuthProvider\";",
    "import { completeLogin } from \"../../lib/blocks/auth\";",
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "import { Alert } from \"../../shared/ui/Alert\";",
    "import { LoadingScreen } from \"../../shared/ui/LoadingScreen\";",
    "",
    "export function CallbackPage({ onNavigate }: { onNavigate: (path: string) => void }) {",
    "  const { refresh } = useAuth();",
    "  const { t } = useT();",
    "  const [error, setError] = useState<string | undefined>();",
    "  const ran = useRef(false);",
    "",
    "  useEffect(() => {",
    "    if (ran.current) return;",
    "    ran.current = true;",
    "",
    "    completeLogin(window.location.href).then((result) => {",
    "      if (result.ok) {",
    "        refresh();",
    "        onNavigate(result.returnTo);",
    "        return;",
    "      }",
    "",
    "      setError(result.message);",
    "    });",
    "  }, [onNavigate, refresh]);",
    "",
    "  if (error) {",
    "    return (",
    "      <div className=\"auth-screen\">",
    "        <div className=\"auth-card\">",
    "          <h2>{t(\"auth.failed\")}</h2>",
    "          <Alert tone=\"error\">{error}</Alert>",
    "          <button className=\"primary-button auth-submit\" onClick={() => onNavigate(\"/login\")}>{t(\"auth.back\")}</button>",
    "        </div>",
    "      </div>",
    "    );",
    "  }",
    "",
    "  return <LoadingScreen />;",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/features/auth/ErrorPage.tsx", [
    "import { AlertTriangle, Home } from \"lucide-react\";",
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "",
    "export function ErrorPage({ onNavigate }: { onNavigate?: (path: string) => void }) {",
    "  const { t } = useT();",
    "  return (",
    "    <section className=\"empty-page\">",
    "      <AlertTriangle size={42} />",
    "      <h2>{t(\"common.error\")}</h2>",
    "      <p>The page could not finish loading. Try again or return to the dashboard.</p>",
    "      <button className=\"primary-button\" onClick={() => onNavigate?.(\"/\")}>",
    "        <Home size={16} /> {t(\"notFound.home\")}",
    "      </button>",
    "    </section>",
    "  );",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/features/auth/NotFoundPage.tsx", [
    "import { Home } from \"lucide-react\";",
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "",
    "export function NotFoundPage({ onNavigate }: { onNavigate: (path: string) => void }) {",
    "  const { t } = useT();",
    "  return (",
    "    <section className=\"not-found\">",
    "      <h2>{t(\"notFound.title\")}</h2>",
    "      <p>{t(\"notFound.message\")}</p>",
    "      <button",
    "        className=\"primary-button\"",
    "        onClick={(event) => {",
    "          event.preventDefault();",
    "          onNavigate(\"/\");",
    "        }}",
    "      >",
    "        <Home size={16} /> {t(\"notFound.home\")}",
    "      </button>",
    "    </section>",
    "  );",
    "}",
    ""
  ].join("\n"));

}
