import { write } from "./fs.js";

// The app's Blocks SDK wiring: runtime config, JWT helpers, the shared blocksClient instance, and the session/auth module.
export async function writeBlocksLib(root: string): Promise<void> {
  await write(root, "src/lib/blocks/config.ts", [
    "export const blocksConfig = {",
    "  apiUrl: import.meta.env.VITE_BLOCKS_API_URL as string,",
    "  appDomain: import.meta.env.VITE_BLOCKS_APP_DOMAIN as string,",
    "  oidcUrl: import.meta.env.VITE_BLOCKS_OIDC_URL as string,",
    "  oidcClientId: (import.meta.env.VITE_BLOCKS_OIDC_CLIENT_ID as string) || \"\",",
    "  oidcScope: (import.meta.env.VITE_BLOCKS_OIDC_SCOPE as string) || \"openid profile\",",
    "  // This project's tenant id -- sent as the x-blocks-key header on every",
    "  // Blocks API call, and as tenant_id on the OIDC login request.",
    "  xBlocksKey: import.meta.env.VITE_BLOCKS_X_BLOCKS_KEY as string",
    "};",
    "",
    "export function isBlocksConfigured(): boolean {",
    "  return Boolean(blocksConfig.apiUrl && blocksConfig.xBlocksKey && blocksConfig.appDomain);",
    "}",
    "",
    "export function isLoginConfigured(): boolean {",
    "  return Boolean(blocksConfig.apiUrl && blocksConfig.oidcUrl && blocksConfig.oidcClientId);",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/lib/blocks/jwt.ts", [
    "export function decodeJwtPayload(token: string): Record<string, unknown> {",
    "  const [, payload] = token.split(\".\");",
    "  if (!payload) throw new Error(\"Invalid JWT: missing payload\");",
    "",
    "  const normalized = payload.replaceAll(\"-\", \"+\").replaceAll(\"_\", \"/\");",
    "  const padded = normalized.padEnd(normalized.length + ((4 - (normalized.length % 4)) % 4), \"=\");",
    "  const binary = atob(padded);",
    "  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));",
    "  return JSON.parse(new TextDecoder().decode(bytes)) as Record<string, unknown>;",
    "}",
    "",
    "export function jwtExpiryMs(token: string): number | undefined {",
    "  const payload = decodeJwtPayload(token);",
    "  return typeof payload.exp === \"number\" ? payload.exp * 1000 : undefined;",
    "}",
    "",
    "export function isJwtExpired(token: string, skewMs = 30_000): boolean {",
    "  let expiry: number | undefined;",
    "  try {",
    "    expiry = jwtExpiryMs(token);",
    "  } catch {",
    "    return true;",
    "  }",
    "  if (!expiry) return false;",
    "  return Date.now() + skewMs >= expiry;",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/lib/blocks/client.ts", [
    "import { createBlocksClient } from \"@seliseblocks/client\";",
    "import { blocksConfig } from \"./config\";",
    "import { forceRefreshAccessToken, getValidAccessToken } from \"./auth\";",
    "",
    "// Single Blocks API entry point for this app -- every Auth, IAM, Data, and",
    "// Localization call goes through this client, never a hand-written fetch().",
    "// `accessToken` is a caller-owned resolver: the SDK reads it before each",
    "// protected call but never stores/refreshes/clears it itself, so the actual",
    "// session lifecycle (storage, refresh-before-expiry) lives in ./auth.ts.",
    "// `onUnauthorized` is the reactive counterpart: it only fires when a call",
    "// comes back 401 despite a locally-valid-looking token (server-side",
    "// revocation, clock skew), and shares the same in-flight refresh as the",
    "// proactive path so concurrent 401s resolve one refresh, not one each.",
    "export const blocksClient = createBlocksClient({",
    "  accessToken: () => getValidAccessToken(),",
    "  apiUrl: blocksConfig.apiUrl,",
    "  appDomain: blocksConfig.appDomain,",
    "  onUnauthorized: () => forceRefreshAccessToken(),",
    "  oidc: {",
    "    clientId: blocksConfig.oidcClientId,",
    "    scope: blocksConfig.oidcScope,",
    "    url: blocksConfig.oidcUrl",
    "  },",
    "  xBlocksKey: blocksConfig.xBlocksKey",
    "});",
    ""
  ].join("\n"));

  await write(root, "src/lib/blocks/auth.ts", [
    "import { blocksClient } from \"./client\";",
    "import { blocksConfig } from \"./config\";",
    "import { isJwtExpired } from \"./jwt\";",
    "",
    "// IAM's hosted IdP flow sets the session as a Secure, httpOnly cookie by",
    "// default -- this app never sees that token and must not try to. Bearer",
    "// tokens below are only populated when a tenant's OIDC config explicitly",
    "// opts into returning tokens in the response body instead of a cookie; in",
    "// the default cookie flow every function below simply no-ops around them.",
    "const TOKEN_KEY = \"blocks-app:access-token\";",
    "const REFRESH_TOKEN_KEY = \"blocks-app:refresh-token\";",
    "const RETURN_KEY = \"blocks-app:oidc-return-to\";",
    "",
    "export type CallbackResult = { ok: true; returnTo: string } | { ok: false; message: string };",
    "",
    "let cachedAccessToken: string | undefined;",
    "let cachedRefreshToken: string | undefined;",
    "let refreshInFlight: Promise<string | undefined> | undefined;",
    "",
    "// AuthProvider subscribes to this to learn the session died out-of-band (a",
    "// refresh came back invalid_grant) so it can flip status to unauthenticated",
    "// and let RequireAuth redirect to /login -- this module has no router access",
    "// of its own to do that navigation directly.",
    "const sessionExpiredListeners = new Set<() => void>();",
    "",
    "export function onSessionExpired(listener: () => void): () => void {",
    "  sessionExpiredListeners.add(listener);",
    "  return () => sessionExpiredListeners.delete(listener);",
    "}",
    "",
    "function notifySessionExpired(): void {",
    "  for (const listener of sessionExpiredListeners) listener();",
    "}",
    "",
    "function getAccessToken(): string | undefined {",
    "  if (cachedAccessToken && !isJwtExpired(cachedAccessToken)) return cachedAccessToken;",
    "",
    "  const stored = sessionStorage.getItem(TOKEN_KEY);",
    "  if (stored && !isJwtExpired(stored)) {",
    "    cachedAccessToken = stored;",
    "    return stored;",
    "  }",
    "",
    "  return undefined;",
    "}",
    "",
    "function getRefreshToken(): string | undefined {",
    "  return cachedRefreshToken ?? sessionStorage.getItem(REFRESH_TOKEN_KEY) ?? undefined;",
    "}",
    "",
    "function persistTokens(accessToken: string, refreshToken?: string): void {",
    "  cachedAccessToken = accessToken;",
    "  sessionStorage.setItem(TOKEN_KEY, accessToken);",
    "",
    "  if (refreshToken) {",
    "    cachedRefreshToken = refreshToken;",
    "    sessionStorage.setItem(REFRESH_TOKEN_KEY, refreshToken);",
    "  }",
    "}",
    "",
    "function clearLocalTokens(): void {",
    "  cachedAccessToken = undefined;",
    "  cachedRefreshToken = undefined;",
    "  sessionStorage.removeItem(TOKEN_KEY);",
    "  sessionStorage.removeItem(REFRESH_TOKEN_KEY);",
    "}",
    "",
    "// Passed to createBlocksClient as the `accessToken` resolver: returns the",
    "// cached token when it's still fresh, otherwise refreshes it through",
    "// blocksClient.auth.oidc.refreshToken() -- concurrent callers share one",
    "// in-flight refresh instead of racing duplicate requests. Resolves to",
    "// undefined in the default cookie flow (nothing cached, nothing to",
    "// refresh); the SDK still sends the session cookie on every request, so",
    "// protected calls keep working without an Authorization header.",
    "export async function getValidAccessToken(): Promise<string | undefined> {",
    "  const current = getAccessToken();",
    "  if (current) return current;",
    "  return forceRefreshAccessToken();",
    "}",
    "",
    "// Passed to createBlocksClient as `onUnauthorized`: unlike getValidAccessToken,",
    "// this skips the \"is the cached token still fresh\" check and always goes",
    "// straight to refreshAccessToken() -- a 401 means the server already",
    "// disagreed with our local judgment of freshness, so re-checking it would",
    "// just resend the same rejected token. Still funnels through the same",
    "// refreshInFlight guard, so a burst of concurrent 401s (and any proactive",
    "// caller racing them) share one refresh call instead of firing one each.",
    "export async function forceRefreshAccessToken(): Promise<string | undefined> {",
    "  const refreshToken = getRefreshToken();",
    "  if (!refreshToken) return undefined;",
    "",
    "  if (!refreshInFlight) {",
    "    refreshInFlight = refreshAccessToken(refreshToken).finally(() => {",
    "      refreshInFlight = undefined;",
    "    });",
    "  }",
    "",
    "  return refreshInFlight;",
    "}",
    "",
    "async function refreshAccessToken(refreshToken: string): Promise<string | undefined> {",
    "  let response: Awaited<ReturnType<typeof blocksClient.auth.oidc.refreshToken>>;",
    "  try {",
    "    response = await blocksClient.auth.oidc.refreshToken({ refreshToken });",
    "  } catch {",
    "    // A network/transport failure here says nothing about whether the",
    "    // refresh token itself is still valid -- keep it cached so the next",
    "    // attempt can still use it, instead of forcing a fresh sign-in over a",
    "    // transient blip (e.g. the dev server restarting mid-session).",
    "    return undefined;",
    "  }",
    "",
    "  const accessToken = response.access_token ?? response.accessToken;",
    "  if (!accessToken) {",
    "    // IAM answered but explicitly rejected the grant (e.g. invalid_grant --",
    "    // the refresh token expired or was already rotated away) -- now it",
    "    // really is dead, so this is a full sign-out, not just a cache clear.",
    "    // Clear local state before the logout call so its own accessToken",
    "    // lookup finds nothing to refresh and doesn't loop back into us.",
    "    clearLocalTokens();",
    "    await blocksClient.auth.logout({ refreshToken }).catch(() => undefined);",
    "    notifySessionExpired();",
    "    return undefined;",
    "  }",
    "",
    "  // The identity provider may not rotate the refresh token on every call --",
    "  // keep the previous one instead of overwriting a working token with undefined.",
    "  const nextRefreshToken = response.refresh_token ?? response.refreshToken ?? refreshToken;",
    "  persistTokens(accessToken, nextRefreshToken);",
    "  return accessToken;",
    "}",
    "",
    "// The session's source of truth is IAM, not a token this app can inspect --",
    "// `GET /iam/v4/auth/me` (blocksClient.auth.userInfo()) validates the",
    "// httpOnly session cookie (or bearer token, if one is cached) and returns",
    "// its claims in one round trip. `iam.me()` is a different, heavier call --",
    "// the full IAM user profile with roles/permissions -- and is used",
    "// separately on the Profile page; it is not a substitute for this check.",
    "export async function fetchSessionClaims(): Promise<Record<string, unknown> | undefined> {",
    "  try {",
    "    return await blocksClient.auth.userInfo();",
    "  } catch {",
    "    return undefined;",
    "  }",
    "}",
    "",
    "export async function startLogin(returnTo?: string): Promise<void> {",
    "  if (!blocksConfig.oidcClientId) {",
    "    throw new Error(\"Login is not configured. Set VITE_BLOCKS_OIDC_CLIENT_ID in .env.\");",
    "  }",
    "",
    "  sessionStorage.setItem(RETURN_KEY, returnTo || \"/\");",
    "  await blocksClient.auth.idp.redirectToProvider();",
    "}",
    "",
    "export async function completeLogin(callbackUrl: string): Promise<CallbackResult> {",
    "  const returnTo = sessionStorage.getItem(RETURN_KEY) || \"/\";",
    "",
    "  sessionStorage.removeItem(RETURN_KEY);",
    "",
    "  const data = await blocksClient.auth.idp.callback(callbackUrl);",
    "",
    "  if (data.error) {",
    "    return { message: data.error_description || data.error, ok: false };",
    "  }",
    "",
    "  // In the default cookie flow IAM sets the session via Set-Cookie on this",
    "  // same response and returns no token in the body -- that's success, not",
    "  // a failure. Only cache a token here if a non-default OIDC config made",
    "  // IAM return one.",
    "  const accessToken = data.access_token ?? data.accessToken;",
    "  if (accessToken) persistTokens(accessToken, data.refresh_token ?? data.refreshToken);",
    "",
    "  return { ok: true, returnTo };",
    "}",
    "",
    "export async function logout(): Promise<void> {",
    "  // Ask IAM to end the session (clears the httpOnly cookie server-side)",
    "  // before dropping any locally cached bearer token; best-effort so a",
    "  // network failure never blocks the user from leaving a protected page.",
    "  await blocksClient.auth.logout({ refreshToken: getRefreshToken() }).catch(() => undefined);",
    "  clearLocalTokens();",
    "}",
    ""
  ].join("\n"));

}
