import { write } from "./fs.js";

// App shell chrome: nav items, the collapsible sidebar + topbar (AppShell), UserMenu, NotificationsMenu.
export async function writeLayout(root: string): Promise<void> {
  await write(root, "src/app/layout/navItems.ts", [
    "import { Boxes, Home, UserRound } from \"lucide-react\";",
    "",
    "export const navItems = [",
    "  { href: \"/\", labelKey: \"nav.dashboard\", icon: Home },",
    "  { href: \"/assets\", labelKey: \"nav.assets\", icon: Boxes },",
    "  { href: \"/profile\", labelKey: \"nav.profile\", icon: UserRound }",
    "] as const;",
    ""
  ].join("\n"));

  await write(root, "src/app/layout/AppShell.tsx", [
    "import { Activity, PanelLeft } from \"lucide-react\";",
    "import { useEffect, useState } from \"react\";",
    "import type { ReactNode } from \"react\";",
    "import { navItems } from \"./navItems\";",
    "import { NotificationsMenu } from \"./NotificationsMenu\";",
    "import { UserMenu } from \"./UserMenu\";",
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "",
    "const COLLAPSED_KEY = \"blocks-app:sidebar-collapsed\";",
    "const MOBILE_QUERY = \"(max-width: 880px)\";",
    "",
    "function useIsMobile(): boolean {",
    "  const [isMobile, setIsMobile] = useState(() => window.matchMedia(MOBILE_QUERY).matches);",
    "",
    "  useEffect(() => {",
    "    const mql = window.matchMedia(MOBILE_QUERY);",
    "    const onChange = () => setIsMobile(mql.matches);",
    "    mql.addEventListener(\"change\", onChange);",
    "    return () => mql.removeEventListener(\"change\", onChange);",
    "  }, []);",
    "",
    "  return isMobile;",
    "}",
    "",
    "export function AppShell({ activePath, children, onNavigate }: { activePath: string; children: ReactNode; onNavigate: (path: string) => void }) {",
    "  const isMobile = useIsMobile();",
    "  const [collapsedPref, setCollapsedPref] = useState(() => localStorage.getItem(COLLAPSED_KEY) === \"true\");",
    "  const { t } = useT();",
    "  // On narrow screens the sidebar is always the icon-only rail below --",
    "  // no separate hamburger/drawer/scrim needed, and no dead-end state where",
    "  // nothing on screen can bring navigation back.",
    "  const collapsed = collapsedPref || isMobile;",
    "  const activeItem = navItems.find((item) => item.href === activePath);",
    "",
    "  useEffect(() => {",
    "    localStorage.setItem(COLLAPSED_KEY, String(collapsedPref));",
    "  }, [collapsedPref]);",
    "",
    "  return (",
    "    <div className=\"shell\">",
    "      <aside className={collapsed ? \"collapsed\" : \"\"}>",
    "        <div className=\"sidebar-header\">",
    "          {collapsed ? null : (",
    "            <a className=\"brand\" href=\"/\" onClick={(event) => { event.preventDefault(); onNavigate(\"/\"); }}>",
    "              <span className=\"brand-mark\"><Activity size={16} /></span>",
    "              <span>Blocks App</span>",
    "            </a>",
    "          )}",
    "          {/* Hidden on mobile by CSS (nothing to toggle -- the rail is always",
    "             collapsed there); on desktop it's the only control that can",
    "             re-expand the sidebar, so it must never be the thing collapsing hides. */}",
    "          <button className=\"icon-button sidebar-collapse-toggle\" onClick={() => setCollapsedPref((value) => !value)} aria-label={collapsed ? \"Expand sidebar\" : \"Collapse sidebar\"}>",
    "            <PanelLeft size={16} />",
    "          </button>",
    "        </div>",
    "        <nav>",
    "          {navItems.map((item) => (",
    "            <a",
    "              key={item.href}",
    "              href={item.href}",
    "              data-tooltip={t(item.labelKey)}",
    "              className={activePath === item.href ? \"active\" : \"\"}",
    "              onClick={(event) => {",
    "                event.preventDefault();",
    "                onNavigate(item.href);",
    "              }}",
    "            >",
    "              <item.icon size={18} />",
    "              {collapsed ? null : <span>{t(item.labelKey)}</span>}",
    "            </a>",
    "          ))}",
    "        </nav>",
    "      </aside>",
    "      <div className=\"content\">",
    "        <header className=\"topbar\">",
    "          {activeItem ? (",
    "            <div className=\"breadcrumb\">",
    "              <activeItem.icon size={16} />",
    "              <span>{t(activeItem.labelKey)}</span>",
    "            </div>",
    "          ) : null}",
    "          <div className=\"topbar-spacer\" />",
    "          <NotificationsMenu />",
    "          <UserMenu onNavigate={onNavigate} />",
    "        </header>",
    "        <main>{children}</main>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/app/layout/UserMenu.tsx", [
    "import { LogOut, UserRound } from \"lucide-react\";",
    "import { useAuth } from \"../providers/AuthProvider\";",
    "import { useCurrentUser, userDisplayName, userInitials } from \"../../features/profile/useCurrentUser\";",
    "import { useT } from \"../../lib/i18n/LocalizationProvider\";",
    "import {",
    "  DropdownMenu,",
    "  DropdownMenuContent,",
    "  DropdownMenuItem,",
    "  DropdownMenuLabel,",
    "  DropdownMenuSeparator,",
    "  DropdownMenuTrigger",
    "} from \"../../shared/ui/dropdown-menu\";",
    "",
    "export function UserMenu({ onNavigate }: { onNavigate: (path: string) => void }) {",
    "  const { logout } = useAuth();",
    "  const { t } = useT();",
    "  const me = useCurrentUser();",
    "  const profile = me.data?.data;",
    "  const name = userDisplayName(profile) || (me.isLoading ? \"Loading...\" : \"Guest\");",
    "  const roles = profile?.roles ?? [];",
    "",
    "  function handleLogout() {",
    "    logout();",
    "    onNavigate(\"/login\");",
    "  }",
    "",
    "  return (",
    "    <DropdownMenu>",
    "      <DropdownMenuTrigger className=\"user-menu-trigger\" aria-label=\"Open user menu\">",
    "        <span className=\"avatar avatar-sm\">{userInitials(profile)}</span>",
    "      </DropdownMenuTrigger>",
    "      <DropdownMenuContent align=\"end\" className=\"min-w-[280px]\">",
    "        <DropdownMenuLabel className=\"flex items-center gap-3 font-normal\">",
    "          <span className=\"avatar avatar-lg\">{userInitials(profile)}</span>",
    "          <div className=\"grid gap-0.5 overflow-hidden\">",
    "            <strong className=\"truncate text-sm font-semibold\">{name}</strong>",
    "            {profile?.email ? <small className=\"truncate text-xs text-[hsl(var(--muted-foreground))]\">{profile.email}</small> : null}",
    "            {roles.length > 0 ? <small className=\"truncate text-xs capitalize text-[hsl(var(--muted-foreground))]\">{roles.join(\", \")}</small> : null}",
    "          </div>",
    "        </DropdownMenuLabel>",
    "        <DropdownMenuSeparator />",
    "        <DropdownMenuItem onSelect={() => onNavigate(\"/profile\")}>",
    "          <UserRound size={18} /> {t(\"nav.profile\")}",
    "        </DropdownMenuItem>",
    "        <DropdownMenuSeparator />",
    "        <DropdownMenuItem destructive onSelect={handleLogout}>",
    "          <LogOut size={18} /> {t(\"nav.logout\")}",
    "        </DropdownMenuItem>",
    "      </DropdownMenuContent>",
    "    </DropdownMenu>",
    "  );",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/app/layout/NotificationsMenu.tsx", [
    "import { Bell, CheckCheck } from \"lucide-react\";",
    "import {",
    "  DropdownMenu,",
    "  DropdownMenuContent,",
    "  DropdownMenuLabel,",
    "  DropdownMenuSeparator,",
    "  DropdownMenuTrigger",
    "} from \"../../shared/ui/dropdown-menu\";",
    "",
    "// Reference-only shell: Blocks does not expose a notifications API, so this",
    "// renders a real, accessible menu with a static empty state rather than",
    "// faking data against a Blocks endpoint that does not exist.",
    "export function NotificationsMenu() {",
    "  return (",
    "    <DropdownMenu>",
    "      <DropdownMenuTrigger className=\"icon-button\" aria-label=\"Notifications\">",
    "        <Bell size={18} />",
    "      </DropdownMenuTrigger>",
    "      <DropdownMenuContent align=\"end\" className=\"min-w-[300px]\">",
    "        <DropdownMenuLabel>Notifications</DropdownMenuLabel>",
    "        <DropdownMenuSeparator />",
    "        <div className=\"flex flex-col items-center gap-2 px-3 py-8 text-center\">",
    "          <CheckCheck size={22} className=\"text-[hsl(var(--muted-foreground))]\" />",
    "          <p className=\"text-sm font-medium\">You're all caught up</p>",
    "          <p className=\"text-xs text-[hsl(var(--muted-foreground))]\">No new notifications right now.</p>",
    "        </div>",
    "      </DropdownMenuContent>",
    "    </DropdownMenu>",
    "  );",
    "}",
    ""
  ].join("\n"));

}
