import { write } from "./fs.js";

// The cn() class-merge helper, the Radix-based shadcn-style DropdownMenu, and the Modal/ConfirmDialog overlays built on it.
export async function writeUiPrimitives(root: string): Promise<void> {
  await write(root, "src/lib/utils.ts", [
    "import { clsx, type ClassValue } from \"clsx\";",
    "import { twMerge } from \"tailwind-merge\";",
    "",
    "// Standard shadcn/ui helper: merges conditional class names, then resolves",
    "// conflicting Tailwind utilities (e.g. two different `p-*` values) so the",
    "// later one wins instead of both landing in the DOM.",
    "export function cn(...inputs: ClassValue[]): string {",
    "  return twMerge(clsx(inputs));",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/shared/ui/dropdown-menu.tsx", [
    "// shadcn/ui \"dropdown-menu\" component, generated for this app's Tailwind",
    "// theme -- a thin, accessible wrapper around Radix's primitive so menus",
    "// get focus trapping, keyboard nav (arrow keys, typeahead, Esc-to-close),",
    "// and outside-click handling for free instead of hand-rolled state.",
    "import * as DropdownMenuPrimitive from \"@radix-ui/react-dropdown-menu\";",
    "import type { ComponentPropsWithoutRef, ElementRef } from \"react\";",
    "import { forwardRef } from \"react\";",
    "import { cn } from \"../../lib/utils\";",
    "",
    "export const DropdownMenu = DropdownMenuPrimitive.Root;",
    "export const DropdownMenuTrigger = DropdownMenuPrimitive.Trigger;",
    "",
    "export const DropdownMenuContent = forwardRef<",
    "  ElementRef<typeof DropdownMenuPrimitive.Content>,",
    "  ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Content>",
    ">(({ className, sideOffset = 8, ...props }, ref) => (",
    "  <DropdownMenuPrimitive.Portal>",
    "    <DropdownMenuPrimitive.Content",
    "      ref={ref}",
    "      sideOffset={sideOffset}",
    "      className={cn(",
    "        \"z-50 min-w-[220px] overflow-hidden rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--popover))] p-1.5 text-[hsl(var(--foreground))] shadow-lg\",",
    "        \"data-[state=open]:animate-[blocks-menu-in_0.12s_ease-out]\",",
    "        className",
    "      )}",
    "      {...props}",
    "    />",
    "  </DropdownMenuPrimitive.Portal>",
    "));",
    "DropdownMenuContent.displayName = \"DropdownMenuContent\";",
    "",
    "export const DropdownMenuLabel = forwardRef<",
    "  ElementRef<typeof DropdownMenuPrimitive.Label>,",
    "  ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Label>",
    ">(({ className, ...props }, ref) => (",
    "  <DropdownMenuPrimitive.Label",
    "    ref={ref}",
    "    className={cn(\"px-2.5 py-2 text-sm font-semibold\", className)}",
    "    {...props}",
    "  />",
    "));",
    "DropdownMenuLabel.displayName = \"DropdownMenuLabel\";",
    "",
    "export const DropdownMenuItem = forwardRef<",
    "  ElementRef<typeof DropdownMenuPrimitive.Item>,",
    "  ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Item> & { destructive?: boolean }",
    ">(({ className, destructive, ...props }, ref) => (",
    "  <DropdownMenuPrimitive.Item",
    "    ref={ref}",
    "    className={cn(",
    "      \"flex cursor-pointer select-none items-center gap-3 rounded-lg px-2.5 py-2.5 text-sm font-medium outline-none\",",
    "      \"data-[highlighted]:bg-[hsl(var(--secondary))]\",",
    "      \"data-[disabled]:pointer-events-none data-[disabled]:opacity-50\",",
    "      destructive ? \"text-[hsl(var(--destructive))]\" : undefined,",
    "      className",
    "    )}",
    "    {...props}",
    "  />",
    "));",
    "DropdownMenuItem.displayName = \"DropdownMenuItem\";",
    "",
    "export const DropdownMenuSeparator = forwardRef<",
    "  ElementRef<typeof DropdownMenuPrimitive.Separator>,",
    "  ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Separator>",
    ">(({ className, ...props }, ref) => (",
    "  <DropdownMenuPrimitive.Separator",
    "    ref={ref}",
    "    className={cn(\"my-1.5 h-px bg-[hsl(var(--border))]\", className)}",
    "    {...props}",
    "  />",
    "));",
    "DropdownMenuSeparator.displayName = \"DropdownMenuSeparator\";",
    ""
  ].join("\n"));


  await write(root, "src/shared/ui/Modal.tsx", [
    "import { useEffect } from \"react\";",
    "import type { ReactNode } from \"react\";",
    "import { X } from \"lucide-react\";",
    "",
    "// A generic overlay used by every create/edit/delete dialog in the app --",
    "// backdrop click and Escape both close it, matching what a native <dialog>",
    "// gives you for free.",
    "export function Modal({ children, onClose, title }: { children: ReactNode; onClose: () => void; title: string }) {",
    "  useEffect(() => {",
    "    function onKeyDown(event: KeyboardEvent) {",
    "      if (event.key === \"Escape\") onClose();",
    "    }",
    "    document.addEventListener(\"keydown\", onKeyDown);",
    "    return () => document.removeEventListener(\"keydown\", onKeyDown);",
    "  }, [onClose]);",
    "",
    "  return (",
    "    <div className=\"modal-backdrop\" role=\"presentation\" onClick={onClose}>",
    "      <div aria-modal=\"true\" className=\"modal\" role=\"dialog\" onClick={(event) => event.stopPropagation()}>",
    "        <div className=\"modal-header\">",
    "          <h3>{title}</h3>",
    "          <button className=\"icon-button\" onClick={onClose} aria-label=\"Close\">",
    "            <X size={18} />",
    "          </button>",
    "        </div>",
    "        {children}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/shared/ui/ConfirmDialog.tsx", [
    "import { Modal } from \"./Modal\";",
    "",
    "export function ConfirmDialog({",
    "  message,",
    "  onCancel,",
    "  onConfirm,",
    "  title",
    "}: { message: string; onCancel: () => void; onConfirm: () => void; title: string }) {",
    "  return (",
    "    <Modal title={title} onClose={onCancel}>",
    "      <p>{message}</p>",
    "      <div className=\"modal-actions\">",
    "        <button className=\"icon-button\" onClick={onCancel}>Cancel</button>",
    "        <button className=\"primary-button danger\" onClick={onConfirm}>Delete</button>",
    "      </div>",
    "    </Modal>",
    "  );",
    "}",
    ""
  ].join("\n"));

}
