import { write } from "./fs.js";

// App entry point and top-level providers: main.tsx, App.tsx, AppProviders (React Query + localization), AuthProvider.
export async function writeAppCore(root: string): Promise<void> {
  await write(root, "src/main.tsx", [
    "import { StrictMode } from \"react\";",
    "import { createRoot } from \"react-dom/client\";",
    "import { App } from \"./app/App\";",
    "import \"./app/styles.css\";",
    "",
    "createRoot(document.getElementById(\"root\")!).render(",
    "  <StrictMode>",
    "    <App />",
    "  </StrictMode>",
    ");",
    ""
  ].join("\n"));

  await write(root, "src/vite-env.d.ts", [
    "/// <reference types=\"vite/client\" />",
    "",
    "interface ImportMetaEnv {",
    "  readonly VITE_BLOCKS_API_URL: string;",
    "  readonly VITE_BLOCKS_APP_DOMAIN: string;",
    "  readonly VITE_BLOCKS_OIDC_URL: string;",
    "  readonly VITE_BLOCKS_OIDC_CLIENT_ID: string;",
    "  readonly VITE_BLOCKS_OIDC_SCOPE?: string;",
    "  readonly VITE_BLOCKS_X_BLOCKS_KEY: string;",
    "  readonly VITE_BLOCKS_DEV_HOST?: string;",
    "  readonly VITE_BLOCKS_DEV_PORT?: string;",
    "}",
    "",
    "interface ImportMeta {",
    "  readonly env: ImportMetaEnv;",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/app/App.tsx", [
    "import { AppProviders } from \"./providers/AppProviders\";",
    "import { AuthProvider } from \"./providers/AuthProvider\";",
    "import { AppRouter } from \"./router/routes\";",
    "",
    "export function App() {",
    "  return (",
    "    <AppProviders>",
    "      <AuthProvider>",
    "        <AppRouter />",
    "      </AuthProvider>",
    "    </AppProviders>",
    "  );",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/app/providers/AppProviders.tsx", [
    "import { QueryClient, QueryClientProvider } from \"@tanstack/react-query\";",
    "import type { ReactNode } from \"react\";",
    "import { LocalizationProvider } from \"../../lib/i18n/LocalizationProvider\";",
    "",
    "const queryClient = new QueryClient({",
    "  defaultOptions: {",
    "    queries: {",
    "      // Without this, every component that mounts a query (e.g. the",
    "      // always-visible UserMenu and the Profile page both querying",
    "      // [\"iam\", \"me\"]) treats cached data as stale immediately and",
    "      // refetches on mount, even seconds after another mount just loaded it.",
    "      staleTime: 30_000,",
    "      refetchOnWindowFocus: false,",
    "      retry: false",
    "    }",
    "  }",
    "});",
    "",
    "export function AppProviders({ children }: { children: ReactNode }) {",
    "  return (",
    "    <QueryClientProvider client={queryClient}>",
    "      <LocalizationProvider>{children}</LocalizationProvider>",
    "    </QueryClientProvider>",
    "  );",
    "}",
    ""
  ].join("\n"));


  await write(root, "src/app/providers/AuthProvider.tsx", [
    "import { createContext, useCallback, useContext, useEffect, useMemo, useState } from \"react\";",
    "import type { ReactNode } from \"react\";",
    "import { fetchSessionClaims, logout as endSession, startLogin } from \"../../lib/blocks/auth\";",
    "",
    "type AuthStatus = \"authenticated\" | \"loading\" | \"unauthenticated\";",
    "",
    "type AuthContextValue = {",
    "  claims: Record<string, unknown> | undefined;",
    "  login: (returnTo?: string) => Promise<void>;",
    "  logout: () => Promise<void>;",
    "  refresh: () => Promise<void>;",
    "  status: AuthStatus;",
    "};",
    "",
    "const AuthContext = createContext<AuthContextValue | undefined>(undefined);",
    "// A long backup interval, not the primary signal -- polling auth/me every",
    "// few seconds would hit IAM constantly even while the tab sits idle in the",
    "// background. Regaining focus (below) is what actually needs to be prompt,",
    "// e.g. after signing out in another tab or the session expiring meanwhile.",
    "const STATUS_POLL_MS = 5 * 60_000;",
    "",
    "export function AuthProvider({ children }: { children: ReactNode }) {",
    "  const [status, setStatus] = useState<AuthStatus>(\"loading\");",
    "  const [claims, setClaims] = useState<Record<string, unknown> | undefined>();",
    "",
    "  // The session's source of truth is IAM's GET /iam/v4/auth/me",
    "  // (blocksClient.auth.userInfo()), not a token this app can inspect --",
    "  // the default hosted login flow sets the session as a Secure, httpOnly",
    "  // cookie that never reaches this app's JS, so a successful call here is",
    "  // what \"signed in\" means, not the presence of a cached access token.",
    "  const refresh = useCallback(async () => {",
    "    const sessionClaims = await fetchSessionClaims();",
    "    setClaims(sessionClaims);",
    "    setStatus(sessionClaims ? \"authenticated\" : \"unauthenticated\");",
    "  }, []);",
    "",
    "  useEffect(() => {",
    "    void refresh();",
    "    const id = window.setInterval(refresh, STATUS_POLL_MS);",
    "",
    "    function onVisible() {",
    "      if (document.visibilityState === \"visible\") void refresh();",
    "    }",
    "    document.addEventListener(\"visibilitychange\", onVisible);",
    "",
    "    return () => {",
    "      window.clearInterval(id);",
    "      document.removeEventListener(\"visibilitychange\", onVisible);",
    "    };",
    "  }, [refresh]);",
    "",
    "  const login = useCallback(async (returnTo?: string) => {",
    "    await startLogin(returnTo);",
    "  }, []);",
    "",
    "  const logout = useCallback(async () => {",
    "    await endSession();",
    "    await refresh();",
    "  }, [refresh]);",
    "",
    "  const value = useMemo<AuthContextValue>(() => ({",
    "    claims,",
    "    login,",
    "    logout,",
    "    refresh,",
    "    status",
    "  }), [claims, login, logout, refresh, status]);",
    "",
    "  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;",
    "}",
    "",
    "export function useAuth(): AuthContextValue {",
    "  const context = useContext(AuthContext);",
    "  if (!context) throw new Error(\"useAuth must be used within AuthProvider\");",
    "  return context;",
    "}",
    ""
  ].join("\n"));

}
