import { write } from "./fs.js";

// Route guards (RequireAuth/RedirectIfAuthenticated) and the hand-rolled history-API router.
export async function writeRouter(root: string): Promise<void> {
  await write(root, "src/app/router/guards.tsx", [
    "import { useEffect } from \"react\";",
    "import type { ReactNode } from \"react\";",
    "import { useAuth } from \"../providers/AuthProvider\";",
    "import { LoadingScreen } from \"../../shared/ui/LoadingScreen\";",
    "",
    "type GuardProps = { children: ReactNode; onNavigate: (path: string) => void };",
    "",
    "// currentPath is passed in from router state rather than read live from",
    "// window.location.pathname: under StrictMode's dev-only double-invoked",
    "// effects, the first invocation's pushState() already mutates",
    "// window.location before the second invocation runs, which would nest the",
    "// returnTo query param (e.g. /login?returnTo=%2Flogin) if read live here.",
    "export function RequireAuth({ children, currentPath, onNavigate }: GuardProps & { currentPath: string }) {",
    "  const { status } = useAuth();",
    "",
    "  useEffect(() => {",
    "    if (status === \"unauthenticated\") {",
    "      onNavigate(`/login?returnTo=${encodeURIComponent(currentPath)}`);",
    "    }",
    "  }, [currentPath, status, onNavigate]);",
    "",
    "  if (status !== \"authenticated\") return <LoadingScreen />;",
    "  return <>{children}</>;",
    "}",
    "",
    "export function RedirectIfAuthenticated({ children, onNavigate }: GuardProps) {",
    "  const { status } = useAuth();",
    "",
    "  useEffect(() => {",
    "    if (status === \"authenticated\") onNavigate(\"/\");",
    "  }, [status, onNavigate]);",
    "",
    "  if (status === \"loading\" || status === \"authenticated\") return <LoadingScreen />;",
    "  return <>{children}</>;",
    "}",
    ""
  ].join("\n"));

  await write(root, "src/app/router/routes.tsx", [
    "import { useEffect, useState } from \"react\";",
    "import { AppShell } from \"../layout/AppShell\";",
    "import { RedirectIfAuthenticated, RequireAuth } from \"./guards\";",
    "import { CallbackPage } from \"../../features/auth/CallbackPage\";",
    "import { ErrorPage } from \"../../features/auth/ErrorPage\";",
    "import { LoginPage } from \"../../features/auth/LoginPage\";",
    "import { NotFoundPage } from \"../../features/auth/NotFoundPage\";",
    "import { DashboardPage } from \"../../features/dashboard/DashboardPage\";",
    "import { AssetsPage } from \"../../features/assets/AssetsPage\";",
    "import { ProfilePage } from \"../../features/profile/ProfilePage\";",
    "",
    "const protectedRoutes = {",
    "  \"/\": DashboardPage,",
    "  \"/assets\": AssetsPage,",
    "  \"/error\": ErrorPage,",
    "  \"/profile\": ProfilePage",
    "};",
    "",
    "export function AppRouter() {",
    "  const [path, setPath] = useState(() => window.location.pathname);",
    "  const [search, setSearch] = useState(() => window.location.search);",
    "",
    "  useEffect(() => {",
    "    const onPopState = () => {",
    "      setPath(window.location.pathname);",
    "      setSearch(window.location.search);",
    "    };",
    "    window.addEventListener(\"popstate\", onPopState);",
    "    return () => window.removeEventListener(\"popstate\", onPopState);",
    "  }, []);",
    "",
    "  function navigate(nextPath: string) {",
    "    const [nextPathname = \"/\", queryString = \"\"] = nextPath.split(\"?\");",
    "    window.history.pushState({}, \"\", nextPath);",
    "    setPath(nextPathname);",
    "    setSearch(queryString ? `?${queryString}` : \"\");",
    "  }",
    "",
    "  if (path === \"/login/callback\") {",
    "    return <CallbackPage onNavigate={navigate} />;",
    "  }",
    "",
    "  if (path === \"/login\") {",
    "    const returnTo = new URLSearchParams(search).get(\"returnTo\") || undefined;",
    "    return (",
    "      <RedirectIfAuthenticated onNavigate={navigate}>",
    "        <LoginPage returnTo={returnTo} />",
    "      </RedirectIfAuthenticated>",
    "    );",
    "  }",
    "",
    "  const Page = protectedRoutes[path as keyof typeof protectedRoutes];",
    "  if (!Page) {",
    "    return <NotFoundPage onNavigate={navigate} />;",
    "  }",
    "",
    "  return (",
    "    <RequireAuth currentPath={path} onNavigate={navigate}>",
    "      <AppShell activePath={path} onNavigate={navigate}>",
    "        <Page />",
    "      </AppShell>",
    "    </RequireAuth>",
    "  );",
    "}",
    ""
  ].join("\n"));

}
